### ISSUE TITLE
Плавающая кнопка и форма добавления дела

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/casepress#48]
#  Кнопка

![image](https://cloud.githubusercontent.com/assets/1852897/11450905/06e87208-95d3-11e5-8d1d-4e78fdce6e1b.png)
# Форма

![image](https://cloud.githubusercontent.com/assets/1852897/11450912/221633ee-95d3-11e5-9996-9b5e6242a903.png)
# Прочее
- Делать надо отдельным плагином.
- Добавление через AJAX
- После того как добавили данные, тут же отобразить ссылку с переходом на страницу дела
# Перспектива
- Зависимость от контекста, если находимся в категории дел, то добавление в ту же категорию.
- Если находимся на странице подразделения, то добавление в то же подразделение.
- Если на странице персоны, то назначение этой персоны ответственным.
- В иных случаях добавление дела на самого себя.

**Comment by Petro-1** [comment]
Добрый день! Сделал как смог плагин-инвалид https://github.com/Petro-1/casepress-newcasebutton Прошу прокомментировать, в том ли я вообще пошел направлении. Новые дела создает, но пока есть следующие проблемы:
- удаленных участников все-равно добавляет, буду разбираться;
- с AJAX пока плохо разобрался, в связи с этим не смогу как указано в задании отобразить ссылку с переходом на страницу дела в том же окне, сделал, что переход выполняется автоматически;
- форма обработки введенных данных нового дела в связи с подключением wp_load.php или admin.php почему-то выдает ошибки, связанные с файлом cases_view.php, хотя я к нему не обращаюсь, не могу понять как это решить, разве что игнорировать их и выводить из него только блок с ссылкой на получившееся дело.
Если считаете, что у меня есть шансы превратить это в нормальный плагин, посоветуйте, пожалуйста, что можно почитать, чтобы лучше понять AJAX в связке с worpdress.

**Comment by yumashev** [comment]
Начато не с того.
Куда то в сложные дебри полез и так делать совсем нельзя и очень дорого и долго.

Правила написания плагинов есть тут http://codex.wordpress.org/%D0%9D%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5_%D0%BF%D0%BB%D0%B0%D0%B3%D0%B8%D0%BD%D0%B0

Если правильно писать плагин то подключать wp load или что то такое не нужно.

По AJAX есть хорошая инструкция тут http://wp-kama.ru/id_2018/ajax-v-wordpress.html

Опять же при соблюдении кодекса все довольно просто.

По сути надо просто на хук wp_footer подключить div
- в нем кнопку http://getbootstrap.com/css/#buttons
- и модальность http://getbootstrap.com/javascript/#modals-examples
+ AJAX

@Petro-1

**Comment by Petro-1** [comment]
Добрый день!
Спасибо за проверку и советы. Вроде разобрался с аяксом и все переделал. Пожалуйста, посмотрите еще раз (https://github.com/Petro-1/casepress-newcasebutton).
Кнопку и окно беру из бутстрапа, поля для формы и сохранение введенных данных делаю через do_action.
Надеюсь, я правильно понимаю в описании задания фразу "Добавление через AJAX", что имеется ввиду именно добавление дела через аякс, но не вывод формы? Потому что если саму форму отправлять через аякс (хоть post, хоть load), то эдитор отображается некорректно, либо полукорректно, но тогда страдают другие поля. 
Осталось две больших проблемы:
- После создания дела почему-то все-равно идет обращение к cases_view.php и вылезают ошибки. Даже не знаю как к этому подступиться, сам к фалйу не обращаюсь, к выполняем в моем плагине хукам вроде никакие функции этого файла не привязаны.
- поле Участники не отображается дальше заголовка на странице с отдельным делом, хотя на страницах дел работает, все условия функции вроде точно также соблюдаются.

**Comment by yumashev** [comment]
пока все ок.
да можно подгружать форму без AJAX.
условие показа кнопки только для дел - не верно. эта кнопка должна быть видна на всех страницах сайта.
+ для красоты можно добавить иконку. в BS это легко делается http://getbootstrap.com/components/#glyphicons-examples

и в первой версии давай сделаем так:
1. только 3 поля: Заголовок, Описание и Подразделение
2. без wp_editor
3. при сохранении создается тип Дело, и ссылка "Перейти в дело" - чтобы перейти в новое дело

**Comment by Petro-1** [comment]
@yumashev сделал, посмотрите, пжлст.

возник вопрос: в функции-обработчике аякса не работают корректно global и static переменные, так как при каждом запросе переданное в них во время работы этой функции значение стирается. Существует ли более простой способ сохранять какие-то значения для использования при следующем вызове функции-обработчика, кроме сохранения через add_option или передачи значения в невидимый элемент и его последующее получение в скрипте и обратную отправку через аякс?
